/* You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t. */

class Solution {
public:
	char findTheDifference(string s, string t) {
		vector<int> F1(26, 0), F2(26, 0);
		for(char c : s) F1[c - 'a']++;
		for(char c : t) F2[c - 'a']++;
		
		for(int i = 0; i < 26; i++)
			if(F1[i] != F2[i])
				return 'a' + i;
		
		return -1;
	}
};